import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Employee } from './employee';

@Injectable({
  providedIn: 'root'
})
export class InMemoryDataService implements InMemoryDbService{
  createDb(){
    const devices= [
      { serialNumber:'AS774675GT', description: 'Asus i5', type:3, ownerId: 10 },
      { serialNumber:'AS123175GT', description: 'Dell Vostro', type:3, ownerId: 0 },
      { serialNumber:'AS770005GT', description: 'Dell Vostro', type:3, ownerId: 17 },
      { serialNumber:'AS779005GT', description: 'Asus i7', type:3, ownerId: 33 },
      { serialNumber:'AS774675ZZ', description: 'Asus i5', type:3, ownerId: 50 },
      { serialNumber:'WW774675ZZ', description: 'iPad 10', type:2, ownerId: 0 },
      { serialNumber:'WW884675ZZ', description: 'iPad 11', type:2, ownerId: 12  },
      { serialNumber:'WW994675ZZ', description: 'Samsung 10', type:2, ownerId: 17 },
      { serialNumber:'CC884675ZZ', description: 'Xiaomi 11t', type:1, ownerId: 10 },
      { serialNumber:'CC004675ZZ', description: 'Samsung S9', type:1, ownerId: 50 },
      
    ];

    const employees = [
      { id: 1, name: 'Grace Clemmitt', email: 'gclemmitt0@vk.com' },
      { id: 2, name: 'Prentiss Hildrew', email: 'phildrew1@cbsnews.com' },
      { id: 3, name: 'Nicol Kordovani', email: 'nkordovani2@ow.ly' },
      { id: 4, name: 'Bentley Bolus', email: 'bbolus3@cnet.com' },
      { id: 5, name: 'Marja Bywaters', email: 'mbywaters4@addtoany.com' },
      { id: 6, name: 'Cord Klosterman', email: 'cklosterman5@mapy.cz' },
      { id: 7, name: 'Lilias Willavoys', email: 'lwillavoys6@noaa.gov' },
      { id: 8, name: 'Deck Baldree', email: 'dbaldree7@cdc.gov' },
      { id: 9, name: 'Sybilla Lythgoe', email: 'slythgoe8@yahoo.co.jp' },
      { id: 10, name: 'Reeba Tatlock', email: 'rtatlock9@xrea.com' },
      { id: 11, name: 'Dorie Balden', email: 'dbaldena@joomla.org' },
      { id: 12, name: 'Aloysia Yates', email: 'ayatesb@yellowbook.com' },
      { id: 13, name: 'Theresa Schlag', email: 'tschlagc@sohu.com' },
      { id: 14, name: "Melantha O'Fielly", email: 'mofiellyd@hubpages.com' },
      { id: 15, name: 'Harp Flintoffe', email: 'hflintoffee@abc.net.au' },
      { id: 16, name: 'Herbie Bonney', email: 'hbonneyf@pen.io' },
      { id: 17, name: 'Gerianne Medd', email: 'gmeddg@seattletimes.com' },
      { id: 18, name: 'May Cunniff', email: 'mcunniffh@wufoo.com' },
      { id: 19, name: 'Leroi Bosdet', email: 'lbosdeti@amazon.de' },
      { id: 20, name: 'Karlene Kinze', email: 'kkinzej@sina.com.cn' },
      { id: 21, name: 'Burch Lumsden', email: 'blumsdenk@ameblo.jp' },
      { id: 22, name: 'Clementius Dooley', email: 'cdooleyl@cnet.com' },
      { id: 23, name: 'Bette-ann Lees', email: 'bleesm@networkadvertising.org' },
      { id: 24, name: 'Donalt Pattle', email: 'dpattlen@salon.com' },
      { id: 25, name: 'Rubetta Nason', email: 'rnasono@furl.net' },
      { id: 26, name: 'Elva Syer', email: 'esyerp@bbb.org' },
      { id: 27, name: 'Gerri Jorn', email: 'gjornq@apple.com' },
      { id: 28, name: 'Padraic Banbury', email: 'pbanburyr@google.com.au' },
      { id: 29, name: 'Leopold Steanson', email: 'lsteansons@phoca.cz' },
      { id: 30, name: 'Terencio McMorran', email: 'tmcmorrant@4shared.com' },
      { id: 31, name: 'Isaiah Dawson', email: 'idawsonu@fastcompany.com' },
      { id: 32, name: 'Shir Arnecke', email: 'sarneckev@ca.gov' },
      { id: 33, name: 'Guthrie Eaglesham', email: 'geagleshamw@privacy.gov.au' },
      { id: 34, name: 'Ollie Jochanany', email: 'ojochananyx@illinois.edu' },
      { id: 35, name: 'Jordan Antoinet', email: 'jantoinety@prlog.org' },
      { id: 36, name: 'Elladine Tindley', email: 'etindleyz@quantcast.com' },
      { id: 37, name: 'Shoshana Simison', email: 'ssimison10@eventbrite.com' },
      { id: 38, name: 'Hillary Wylie', email: 'hwylie11@google.ru' },
      { id: 39, name: 'Keven Aldis', email: 'kaldis12@unc.edu' },
      { id: 40, name: 'Olia Hancorn', email: 'ohancorn13@feedburner.com' },
      { id: 41, name: 'Davis Bragge', email: 'dbragge14@wp.com' },
      { id: 42, name: 'Adeline Pavluk', email: 'apavluk15@dagondesign.com' },
      { id: 43, name: 'Brantley Segeswoeth', email: 'bsegeswoeth16@psu.edu' },
      { id: 44, name: 'Ambros Manoch', email: 'amanoch17@apple.com' },
      { id: 45, name: 'Kris Wraighte', email: 'kwraighte18@blogspot.com' },
      { id: 46, name: 'Ronnie Mackleden', email: 'rmackleden19@imdb.com' },
      { id: 47, name: 'Doro Sheavills', email: 'dsheavills1a@rakuten.co.jp' },
      { id: 48, name: 'Trever Alvin', email: 'talvin1b@imdb.com' },
      { id: 49, name: 'Tarrah Raatz', email: 'traatz1c@dmoz.org' },
      { id: 50, name: 'Betta Helis', email: 'bhelis1d@about.com' },
      { id: 51, name: 'Barb Buske', email: 'bbuske1e@amazon.com' },
      { id: 52, name: 'Yevette Savaage', email: 'ysavaage1f@spiegel.de' },
      { id: 53, name: 'Adolf Bore', email: 'abore1g@fda.gov' },
      { id: 54, name: 'Brooks Woollcott', email: 'bwoollcott1h@arizona.edu' },
      { id: 55, name: 'Ferdinande Alenikov', email: 'falenikov1i@admin.ch' },
      { id: 56, name: 'Stanley Northidge', email: 'snorthidge1j@friendfeed.com' },
      {
        id: 57,
        name: 'Gaylene Sonnenschein',
        email: 'gsonnenschein1k@eventbrite.com',
      },
      { id: 58, name: 'Sena Ubanks', email: 'subanks1l@fastcompany.com' },
      { id: 59, name: 'Ara Sherratt', email: 'asherratt1m@flavors.me' },
      { id: 60, name: 'Valera Smithson', email: 'vsmithson1n@cornell.edu' },
      { id: 61, name: 'Bari Mesnard', email: 'bmesnard1o@intel.com' },
      { id: 62, name: 'Barbey Bisley', email: 'bbisley1p@themeforest.net' },
      { id: 63, name: 'Danyette Buzek', email: 'dbuzek1q@woothemes.com' },
      { id: 64, name: 'Pansie Leyton', email: 'pleyton1r@tinyurl.com' },
      { id: 65, name: 'Vyky Ridhole', email: 'vridhole1s@theglobeandmail.com' },
      { id: 66, name: 'Corissa Stoves', email: 'cstoves1t@nyu.edu' },
      { id: 67, name: 'Fowler Perch', email: 'fperch1u@bloglines.com' },
      { id: 68, name: 'Trudie Larchiere', email: 'tlarchiere1v@theatlantic.com' },
      { id: 69, name: 'Manolo Bullion', email: 'mbullion1w@spotify.com' },
      { id: 70, name: 'Halli Amphlett', email: 'hamphlett1x@census.gov' },
      { id: 71, name: 'Jerri Goulbourn', email: 'jgoulbourn1y@diigo.com' },
      { id: 72, name: 'Reggie Penas', email: 'rpenas1z@bloomberg.com' },
      { id: 73, name: 'Elenore Norkutt', email: 'enorkutt20@oaic.gov.au' },
      { id: 74, name: 'Chad Feveryear', email: 'cfeveryear21@sogou.com' },
      { id: 75, name: 'Elisabet Birkbeck', email: 'ebirkbeck22@unicef.org' },
      { id: 76, name: 'Kerwinn Roscrigg', email: 'kroscrigg23@disqus.com' },
      { id: 77, name: 'Bran Lushey', email: 'blushey24@hexun.com' },
      { id: 78, name: 'Iver Treat', email: 'itreat25@pbs.org' },
      { id: 79, name: 'Bren Slinn', email: 'bslinn26@webs.com' },
      { id: 80, name: 'Edyth Mengue', email: 'emengue27@ovh.net' },
      { id: 81, name: 'Lindon Gabbidon', email: 'lgabbidon28@sohu.com' },
      { id: 82, name: 'Patrica Udale', email: 'pudale29@github.io' },
      { id: 83, name: "Stern O' Culligan", email: 'so2a@skyrock.com' },
      { id: 84, name: 'Miquela Vanyukhin', email: 'mvanyukhin2b@seattletimes.com' },
      { id: 85, name: 'Kendrick Scotchford', email: 'kscotchford2c@reuters.com' },
      { id: 86, name: 'Bord Triggel', email: 'btriggel2d@artisteer.com' },
      { id: 87, name: 'Jase Vanns', email: 'jvanns2e@about.com' },
      {
        id: 88,
        name: 'Fredrick Gainsborough',
        email: 'fgainsborough2f@themeforest.net',
      },
      { id: 89, name: 'Ladonna Godlee', email: 'lgodlee2g@oracle.com' },
      { id: 90, name: 'Gilemette Jillard', email: 'gjillard2h@mysql.com' },
      { id: 91, name: 'Olimpia Kidds', email: 'okidds2i@alexa.com' },
      { id: 92, name: 'Anabel Hedworth', email: 'ahedworth2j@microsoft.com' },
      { id: 93, name: 'Farleigh Cridlan', email: 'fcridlan2k@google.es' },
      { id: 94, name: 'Beverlie Croall', email: 'bcroall2l@symantec.com' },
      { id: 95, name: 'Morgana Pesik', email: 'mpesik2m@posterous.com' },
      { id: 96, name: 'Alina Killeley', email: 'akilleley2n@apple.com' },
      { id: 97, name: 'Jerad Hune', email: 'jhune2o@si.edu' },
      { id: 98, name: 'Land Birkmyr', email: 'lbirkmyr2p@technorati.com' },
      { id: 99, name: 'Bartholemy Scobie', email: 'bscobie2q@sfgate.com' },
      { id: 100, name: 'Anna Courtes', email: 'acourtes2r@github.com' },
      { id: 101, name: 'Laughton Tebb', email: 'ltebb2s@biglobe.ne.jp' },
      { id: 102, name: 'Valle de Juares', email: 'vde2t@rakuten.co.jp' },
      { id: 103, name: 'Corina Rapin', email: 'crapin2u@about.me' },
      { id: 104, name: 'Adah McFetridge', email: 'amcfetridge2v@tamu.edu' },
      { id: 105, name: 'Ellary Janu', email: 'ejanu2w@acquirethisname.com' },
      { id: 106, name: 'Emilia Bowlands', email: 'ebowlands2x@homestead.com' },
      {
        id: 107,
        name: 'Chandler Jakoviljevic',
        email: 'cjakoviljevic2y@hexun.com',
      },
      { id: 108, name: 'Berny Cockrell', email: 'bcockrell2z@fotki.com' },
      { id: 109, name: 'Annamarie Comelini', email: 'acomelini30@mediafire.com' },
      { id: 110, name: 'Terence Cattermole', email: 'tcattermole31@wired.com' },
      { id: 111, name: 'Kally Bartens', email: 'kbartens32@tmall.com' },
      { id: 112, name: 'Gordie Millimoe', email: 'gmillimoe33@myspace.com' },
      { id: 113, name: 'Francklyn Andrelli', email: 'fandrelli34@cnbc.com' },
      { id: 114, name: 'Trisha Burtonwood', email: 'tburtonwood35@tuttocitta.it' },
      { id: 115, name: 'Ray Guppey', email: 'rguppey36@virginia.edu' },
      { id: 116, name: 'Hesther Baack', email: 'hbaack37@freewebs.com' },
      { id: 117, name: 'Buddy Tillot', email: 'btillot38@dagondesign.com' },
      { id: 118, name: 'Michaella Kenen', email: 'mkenen39@sphinn.com' },
      { id: 119, name: 'Kathleen Hartnup', email: 'khartnup3a@vkontakte.ru' },
      { id: 120, name: 'Candie McPhater', email: 'cmcphater3b@jugem.jp' },
      { id: 121, name: 'Hamel Errey', email: 'herrey3c@youtube.com' },
      { id: 122, name: 'Ailbert Deny', email: 'adeny3d@theglobeandmail.com' },
      { id: 123, name: 'Nesta Biggs', email: 'nbiggs3e@furl.net' },
      { id: 124, name: 'Rayshell Mackison', email: 'rmackison3f@mapquest.com' },
      { id: 125, name: 'Shelley Klimuk', email: 'sklimuk3g@blinklist.com' },
      { id: 126, name: 'Aleen Ortet', email: 'aortet3h@blogs.com' },
      { id: 127, name: 'Lonna Butterick', email: 'lbutterick3i@hc360.com' },
      { id: 128, name: 'Raymund Craigie', email: 'rcraigie3j@epa.gov' },
      { id: 129, name: 'Rani Rosindill', email: 'rrosindill3k@yellowpages.com' },
      { id: 130, name: 'Clemence Stockell', email: 'cstockell3l@newsvine.com' },
      { id: 131, name: 'Berti Okeshott', email: 'bokeshott3m@goo.ne.jp' },
      { id: 132, name: "Loise De L'Isle", email: 'lde3n@wp.com' },
      { id: 133, name: 'Kendra Cargo', email: 'kcargo3o@adobe.com' },
      { id: 134, name: 'Lincoln Endecott', email: 'lendecott3p@google.fr' },
      { id: 135, name: 'Benjie Sign', email: 'bsign3q@unc.edu' },
      { id: 136, name: 'Ana Nelius', email: 'anelius3r@va.gov' },
      { id: 137, name: 'Rhetta Yakobovicz', email: 'ryakobovicz3s@salon.com' },
      { id: 138, name: 'Demott Broomhead', email: 'dbroomhead3t@yale.edu' },
      { id: 139, name: 'Lola Idel', email: 'lidel3u@sourceforge.net' },
      { id: 140, name: 'Tobe Roath', email: 'troath3v@last.fm' },
      { id: 141, name: 'Spense Silson', email: 'ssilson3w@dailymail.co.uk' },
      { id: 142, name: 'Berrie Hasard', email: 'bhasard3x@jimdo.com' },
      { id: 143, name: 'Tull Kuna', email: 'tkuna3y@nsw.gov.au' },
      { id: 144, name: 'Giuseppe Ferroni', email: 'gferroni3z@hp.com' },
      { id: 145, name: 'Wylma Collicott', email: 'wcollicott40@cnet.com' },
      {
        id: 146,
        name: 'Somerset Winnard',
        email: 'swinnard41@merriam-webster.com',
      },
      { id: 147, name: 'Honey Slingsby', email: 'hslingsby42@google.fr' },
      { id: 148, name: 'Kalinda Hutten', email: 'khutten43@blogspot.com' },
      { id: 149, name: 'Gerianna Wheeliker', email: 'gwheeliker44@usatoday.com' },
      { id: 150, name: 'Aloise Rekes', email: 'arekes45@booking.com' },
      { id: 151, name: 'Julissa Jonczyk', email: 'jjonczyk46@sourceforge.net' },
      { id: 152, name: 'Elise Baselli', email: 'ebaselli47@blinklist.com' },
      { id: 153, name: 'Loleta Nower', email: 'lnower48@yandex.ru' },
      { id: 154, name: 'Ginelle Drury', email: 'gdrury49@exblog.jp' },
      { id: 155, name: 'Hubey Gamon', email: 'hgamon4a@earthlink.net' },
      { id: 156, name: 'Lita Pichan', email: 'lpichan4b@narod.ru' },
      { id: 157, name: 'Madlin Olanda', email: 'molanda4c@state.tx.us' },
      { id: 158, name: 'Sayres Abbati', email: 'sabbati4d@redcross.org' },
      { id: 159, name: 'Marjie Lumsdall', email: 'mlumsdall4e@bing.com' },
      { id: 160, name: 'Gamaliel Aldcorn', email: 'galdcorn4f@google.es' },
      { id: 161, name: 'Hyman Otley', email: 'hotley4g@mashable.com' },
      { id: 162, name: 'Matthus Brittlebank', email: 'mbrittlebank4h@go.com' },
      { id: 163, name: 'Grissel Innis', email: 'ginnis4i@comsenz.com' },
      { id: 164, name: 'Valentijn Boyda', email: 'vboyda4j@unicef.org' },
      { id: 165, name: 'Winfred Dranfield', email: 'wdranfield4k@hubpages.com' },
      {
        id: 166,
        name: 'Diandra Petchell',
        email: 'dpetchell4l@nationalgeographic.com',
      },
      { id: 167, name: 'Fanchette Mudge', email: 'fmudge4m@themeforest.net' },
      { id: 168, name: 'Arabelle Tungay', email: 'atungay4n@bloglines.com' },
      { id: 169, name: 'Gwenni Bernadot', email: 'gbernadot4o@amazon.co.jp' },
      { id: 170, name: 'Zea Odams', email: 'zodams4p@independent.co.uk' },
      { id: 171, name: 'Berny Fasey', email: 'bfasey4q@smugmug.com' },
      { id: 172, name: 'Benedetta Dyers', email: 'bdyers4r@dedecms.com' },
      { id: 173, name: 'Adiana Ummfrey', email: 'aummfrey4s@weibo.com' },
      { id: 174, name: 'Roxine Costerd', email: 'rcosterd4t@t-online.de' },
      { id: 175, name: 'Karen Craine', email: 'kcraine4u@foxnews.com' },
      { id: 176, name: 'Goldi Marty', email: 'gmarty4v@typepad.com' },
      { id: 177, name: 'Kelcey Basterfield', email: 'kbasterfield4w@nps.gov' },
      { id: 178, name: 'Eloisa Chamberlen', email: 'echamberlen4x@zdnet.com' },
      { id: 179, name: 'Verne Hannay', email: 'vhannay4y@pcworld.com' },
      { id: 180, name: 'Larry Ashbey', email: 'lashbey4z@unesco.org' },
      { id: 181, name: 'Lek Brigstock', email: 'lbrigstock50@altervista.org' },
      { id: 182, name: 'Nicolais Kennea', email: 'nkennea51@google.fr' },
      {
        id: 183,
        name: 'Fredericka Bispham',
        email: 'fbispham52@merriam-webster.com',
      },
      { id: 184, name: 'Bailie Tatem', email: 'btatem53@godaddy.com' },
      { id: 185, name: 'Adoree Dandy', email: 'adandy54@tiny.cc' },
      { id: 186, name: 'Leisha Gliddon', email: 'lgliddon55@arizona.edu' },
      { id: 187, name: 'Bethanne Hearsey', email: 'bhearsey56@youtu.be' },
      { id: 188, name: 'Avril Giacovetti', email: 'agiacovetti57@usa.gov' },
      { id: 189, name: 'Dayna Wiltshier', email: 'dwiltshier58@phpbb.com' },
      { id: 190, name: 'Benny Kunrad', email: 'bkunrad59@clickbank.net' },
      { id: 191, name: 'Monique Butson', email: 'mbutson5a@wufoo.com' },
      { id: 192, name: 'Oralle Schlag', email: 'oschlag5b@baidu.com' },
      { id: 193, name: 'Gerome Harnott', email: 'gharnott5c@cbslocal.com' },
      { id: 194, name: 'Chantal Taffurelli', email: 'ctaffurelli5d@illinois.edu' },
      { id: 195, name: 'Laurena Guinn', email: 'lguinn5e@plala.or.jp' },
      { id: 196, name: 'Liam Kenney', email: 'lkenney5f@gizmodo.com' },
      { id: 197, name: 'Chad Panswick', email: 'cpanswick5g@state.gov' },
      {
        id: 198,
        name: 'Frederique Hackney',
        email: 'fhackney5h@businessinsider.com',
      },
      { id: 199, name: 'Isobel Inglesant', email: 'iinglesant5i@netvibes.com' },
      { id: 200, name: 'Ardath Bilham', email: 'abilham5j@topsy.com' },
    ];

    return {devices, employees};
  }

     
    genId(employees: Employee[]): number {
      return employees.length > 0 ? Math.max(...employees.map(empl => empl.id)) + 1 : 200;
    }
}

      

